version: "3.3"

services:
  punch_clock:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: punch-clock
    ports:
      - 80:80/tcp
    environment:
      TZ: "America/Sao_Paulo"
      ENV: "production"  # development|production
    hostname: punchclock.local
    volumes:
      - ./db:/var/db
      - ./log:/var/log
    restart: unless-stopped
